### ISSUE TITLE
Cannot install Nuget package for Android

### ISSUE THREAD

**Issue by JohnMcAvinue** [BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK#10]
I'm trying to install the 1.1.1 version using Nuget but I'm getting this error:

Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I'm using VS2015. Perhaps it's related to this bug with Nuget?

https://github.com/NuGet/Home/issues/1707

**Comment by aaustin** [comment]
@JohnMcAvinue What version of Nuget are you using? We've never seen this error before unfortunately. Can you try adding it with Xamarin Studio, then migrating it to VS?

**Comment by JohnMcAvinue** [comment]
@aaustin Hi Alex, I can't find anything from Branch.io on the Component Store? I just updated to the latest version of Nuget package manager and I'm still getting the same error

**Comment by aaustin** [comment]
Hey @JohnMcAvinue - This is the one you're looking for I believe https://www.nuget.org/packages/Branch-Xamarin-Linking-SDK. There's an engineer working to try to replicate the issue you're seeing now.

**Comment by JohnMcAvinue** [comment]
@aaustin Hi Austin, that is the Nuget package I am having problems with. Here's the Nuget console log when I try to install:

Package Manager Console Host Version 3.3.0.167

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package Branch-Xamarin-Linking-SDK
Attempting to gather dependencies information for package 'Branch-Xamarin-Linking-SDK.1.1.1' with respect to project 'EPH.Mobile.Droid', targeting 'MonoAndroid,Version=v6.0'
Attempting to resolve dependencies for package 'Branch-Xamarin-Linking-SDK.1.1.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Branch-Xamarin-Linking-SDK.1.1.1'
Resolved actions to install package 'Branch-Xamarin-Linking-SDK.1.1.1'
Install failed. Rolling back...
Package 'Microsoft.Bcl.Build.1.0.14 : ' does not exist in project 'EPH.Mobile.Droid'
Package 'Microsoft.Bcl.Build.1.0.14 : ' does not exist in folder 'C:\SourceCode\EPH\trunk\Mobile\packages'
Install-Package : Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project that targets 
'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, 
contact the package author.
At line:1 char:1
+ Install-Package Branch-Xamarin-Linking-SDK
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by antonargunov** [comment]
Hello @JohnMcAvinue 
Try this solution:
1) Install package Microsoft.Bc.Build.1.0.21 at first
2) Then install package Branch-Xamarin-Linking-SDK

**Comment by JohnMcAvinue** [comment]
That worked for me thanks

**Comment by kevindfs** [comment]
@antonargunov your workaround work for me. Thanks! (Using VS Comunity)

**Comment by antonargunov** [comment]
@kevindfs glad to hear that!

**Comment by aswathigi** [comment]
Hi,

I am getting this error while trying to install WindowsAzure.MobileServices
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.Bcl 1.1.9'. You are trying to install this package into a project that targets 'MDD,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	


I have tried the above stuffs and its not working for me.

REgards,
Aswathi

**Comment by antonargunov** [comment]
HI @aswathigi ,
I have several questions:
1) what platform? (iOS, Android)
2) what type of project? (cross-platform, iOS, Android)
3) Xamarin or VS 2015?

Note: Branch Xamarin SDK doesn't support Windows mobile platforms

**Comment by aswathigi** [comment]
Hello,

Thank you for getting back to me. I am using VS 2015.
Its a cross platform project of - Cordova, Phonegap with Ionic framework. I
was trying to install "Azure Mobile Apps". later i have added it from
config.xml. But still i am not able to get my authentication correctly.

thanks & Regards,
Aswathi

**Comment by antonargunov** [comment]
HI @aswathigi , sorry for delay.
For my curiosity, I tried to create Cordova + Ionic project, but I have the same issue.
As I understand that is trouble with Window Mobile Universal/Window Mobile 8.1.
Try to find solution with Microsoft + Ionic community. Or try to delete support Window Mobile platforms.
Sorry but I can't help you with your issue.

**Comment by kevindfs** [comment]
Hi @aswathigi ,
Try this solution:
1) Install package Microsoft.Bcl.Build.1.0.21 at first
2) Install package Microsoft.Bcl 1.1.9
3) Install package WindowsAzure.MobileServices
Regards,
Kevin Farías

**Comment by aswathigi** [comment]
Hello Kevin,

Thank you for your mail and info.  I have installed Microsoft.Bcl.Build.1.0.21.
The other 2 i was not able to install. It is giving me errors;
"Attempting to gather dependency information for package
'Microsoft.Bcl.Async.1.0.168' with respect to project 'BlankCordovaApp3',
targeting 'MDD,Version=v8.1'".

My actual requirement is to connect to a share point site and get list of
items for mobile apps.  Please let me know if you have  any alternative
options.

Regards,
Aswathi

**Comment by tommy1999x** [comment]
Hi,

I want to build the app with MongoDB so I install mongocsharpdriver from Nuget.
But I get the error message about "MonoAndroid,Version=v6.0".

> Adding mongocsharpdriver...
Attempting to resolve dependency 'MongoDB.Bson (≥ 2.2.4)'.
Attempting to resolve dependency 'MongoDB.Driver.Core (≥ 2.2.4)'.
Attempting to resolve dependency 'MongoDB.Driver (≥ 2.2.4)'.
The MongoDB.Bson package has a license agreement which is available at http://www.apache.org/licenses/LICENSE-2.0
Please review this license agreement and remove the package if you do not accept the agreement.
Check the package for additional dependencies which may also have license agreements.
Using this package and any dependencies constitutes your acceptance of these license agreements.
The mongocsharpdriver package has a license agreement which is available at http://www.apache.org/licenses/LICENSE-2.0
Please review this license agreement and remove the package if you do not accept the agreement.
Check the package for additional dependencies which may also have license agreements.
Using this package and any dependencies constitutes your acceptance of these license agreements.
Installing 'MongoDB.Bson 2.2.4'.
Added file 'MongoDB.Bson.dll' to folder 'MongoDB.Bson.2.2.4\lib\net45'.
Added file 'MongoDB.Bson.XML' to folder 'MongoDB.Bson.2.2.4\lib\net45'.
Added file 'License.rtf' to folder 'MongoDB.Bson.2.2.4'.
Added file 'MongoDB.Bson.2.2.4.nupkg' to folder 'MongoDB.Bson.2.2.4'.
Successfully installed 'MongoDB.Bson 2.2.4'.
Installing 'mongocsharpdriver 2.2.4'.
Added file 'MongoDB.Driver.Legacy.dll' to folder 'mongocsharpdriver.2.2.4\lib\net45'.
Added file 'MongoDB.Driver.Legacy.XML' to folder 'mongocsharpdriver.2.2.4\lib\net45'.
Added file 'License.rtf' to folder 'mongocsharpdriver.2.2.4'.
Added file 'mongocsharpdriver.2.2.4.nupkg' to folder 'mongocsharpdriver.2.2.4'.
Successfully installed 'mongocsharpdriver 2.2.4'.
Adding 'MongoDB.Bson 2.2.4' to SunCalen.Droid.
Could not install package 'MongoDB.Bson 2.2.4'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I have tried these ways:
(1)Install Microsoft.Bcl and Microsoft.Bcl.Build
(2)Update Nuget (3.4.3.855)

Platform: Android
Project: Cross-Platform
Both of VS2015 and Xamarin

thanks & Regards,
Tommy

**Comment by Quico20** [comment]
Thanks for you solution, it also worked for me pal!!! great resource forum!!!

**Comment by rubgithub** [comment]
"frameworks": {
    "MonoAndroid,Version=v6.0": { }
  },

**Comment by Emixam23** [comment]
So broken xD Thank for the solution !

**Comment by deanilvincent** [comment]
Sadly, I found this error when I'm trying to install the Brach-Xamarin-Linking-SDK 3.0.5

Could not install package 'Branch-Xamarin-Linking-SDK 3.0.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by aaustin** [comment]
@antonargunov Can you take a look here?

**Comment by antonargunov** [comment]
Hi @deanilvincent ,
we use PCL profile 78.

You should delete WindowPhone 8.1 In PCL project from Targets to change PCL profile from 259 to 78:
1) Uninstall Xamarin Forms package (if you use Xamarin Forms)
2) Delete WindowPhone 8.1 from Targets 
3) Install Xamarin Forms package (if you use Xamarin Forms)

**Comment by mahapajapati** [comment]
Hi,
Sadly, I have a similiar error to JohnMcAvinue, here is the detail:

PM> install-package xmlrpcnet -Version 2.5.0

You are trying to install this package into a project that targets 'MonoAndroid,Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ install-package xmlrpcnet -Version 2.5.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

I´ve already installed succesfully the package Microsoft.Bcl.Build.1.0.21. But I´m still getting the same error above.

I have the 3.4.4 nuget version. Using VS2015 in the Android platform.

Do you have any ideas?

**Comment by Emixam23** [comment]
Hey guys, sorry to back back that late !

I found a solution, that's weird but it works.

So you have 3 packages that are:
-Microsoft.Bcl
-Microsoft.Bcl.Build
-Microsoft.Bcl.Net
(If I'm wrong, sorry, I'm in a road trip, no computer 9

If you try to install, 2 of them will throw you that it's not possible to install blablabla. Bullshit ! Sometimes, it only depends in which order you install them.

So try to install them, based on the dependency description, one by one, and after that, the 3 of them (that aren't possible to install, hmm), are installed :)

Hope it helps !

Max

**Comment by deanilvincent** [comment]
I was abled to fix this properly by installing the 

**Microsoft.Bcl.Build** 
first and then follow by 
**Microsoft.Build.** I hope it works on your end.

**Comment by mahapajapati** [comment]
Thank you for the response. I correctly installed Microsoft.Bcl.Build, Microsoft.Build and Microsoft.Build.Async but it still doesn't work :(

**Comment by Emixam23** [comment]
Can you please post the output of the fail ? :)

**Comment by mahapajapati** [comment]
The fail:

Attempting to gather dependencies information for package 'xmlrpcnet.2.5.0' with respect to project 'CODIGO_BARRAS', targeting 'MonoAndroid,Version=v5.0'
Attempting to resolve dependencies for package 'xmlrpcnet.2.5.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'xmlrpcnet.2.5.0'
Resolved actions to install package 'xmlrpcnet.2.5.0'
Install failed. Rolling back...
Package 'xmlrpcnet.2.5.0' does not exist in project 'CODIGO_BARRAS'
Package 'xmlrpcnet.2.5.0' does not exist in folder 'C:\Users\admin\Documents\Visual Studio 2015\Projects\CODIGO_BARRAS\CODIGO_BARRAS\packages'
Install-Package : Could not install package 'xmlrpcnet.2.5.0'. You are trying to install this package into a project that targets
'MonoAndroid,Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information,
contact the package author.

**Comment by ankitpatel8055** [comment]
@deanilvincent  i think you are selecting class library instead of selecting android project

**Comment by AyoubSannouti** [comment]
Hello guys,

I'm trying to install GooglePlayServices.Maps 60.11.42.1 using Nuget but I'm getting this error:

Could not install package 'Xamarin.GooglePlayServices.Maps 60.1142.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v7.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I'm using VS2015. Perhaps it's related to this bug with Nuget?
