### ISSUE TITLE
Cannot setup Android NonForms project - missing methods

### ISSUE THREAD

**Issue by zoltharpl** [BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK#12]
Hi,

To setup Non Forms Android project in documentation are following lines:

public class MainActivity : Activity, IBranchSessionInterface
{
	protected override void OnCreate (Bundle savedInstanceState)
	{
		base.OnCreate (savedInstanceState);

		global::Xamarin.Forms.Forms.Init (this, savedInstanceState);

		BranchAndroid.Init (this, "your branch key here", Intent.Data, Intent.Extras);

		App app = new App ();

		// Call this method to enable automatic session management
		BranchAndroid.getInstance().SetLifeCycleHandlerCallback (this, app);

		LoadApplication (app);
	}
	
	// Ensure we get the updated link identifier when the app is opened from the
	// background with a new link.
	protected override void OnNewIntent(Intent intent) {
		BranchAndroid.GetInstance().SetNewUrl(intent.Data);
	}

	#region IBranchSessionInterface implementation
	
	public void InitSessionComplete (Dictionary<string, object> data)
	{
		// Do something with the referring link data...
	}

	public void CloseSessionComplete ()
	{
		// Handle any additional cleanup after the session is closed
	}

	public void SessionRequestError (BranchError error)
	{
		// Handle the error case here
	}

	#endregion
}

Problem is that I'm not using Forms and also method SetLifeCycleHandlerCallback  doesn't exists.
Init method also takes only 4 parameters not 5 as in examples.

I'm using SDK Version 1.2 and VS2015

Am I doing it wrong or documentation is not accurate?

**Comment by antonargunov** [comment]
Hello @zoltharpl, thanks for the report, we are solving this issue. Wait please a little bit.

**Comment by antonargunov** [comment]
@zoltharpl, you are right, this is the mistake in the documentation,
please try this solution, we will update our documentation soon.
  
```C#
public class MainActivity : Activity, IBranchSessionInterface
{
	protected override void OnCreate (Bundle savedInstanceState)
	{
		base.OnCreate (savedInstanceState);

		BranchAndroid.Init (this, "your branch key here", Intent.Data, Intent.Extras);

		// Call this method to enable automatic session management
		BranchAndroid.getInstance().SetLifeCycleHandlerCallback (this, this);
	}

	// Ensure we get the updated link identifier when the app is opened from the
	// background with a new link.
	protected override void OnNewIntent(Intent intent) {
		BranchAndroid.getInstance().SetNewUrl(intent.Data);
	}

	#region IBranchSessionInterface implementation

	public void InitSessionComplete (Dictionary<string, object> data)
	{
		// Do something with the referring link data...
	}

	public void CloseSessionComplete ()
	{
		// Handle any additional cleanup after the session is closed
	}

	public void SessionRequestError (BranchError error)
	{
		// Handle the error case here
	}

	#endregion
}
```

**Comment by antonargunov** [comment]
@zoltharpl,
We have updated the documentation.

**Comment by zoltharpl** [comment]
Thank you! When Nuget will be available?

**Comment by antonargunov** [comment]
@zoltharpl, nuget package is already available:
https://www.nuget.org/packages/Branch-Xamarin-Linking-SDK/

**Comment by zoltharpl** [comment]
Thank you, I will check it :)

You guys work fast :)

**Comment by antonargunov** [comment]
Thank you! :)
