### ISSUE TITLE
Branch Xamarin.iOS SDK Integration, first time installation Branch WebServices timeout.

### ISSUE THREAD

**Issue by venky284** [BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK#16]
This is the Console output which I get,

2016-03-18 12:07:30.150 BranchTest[285:22062] Sending Install request
2016-03-18 12:07:30.222 BranchTest[285:22062] DidBecomeActive Automatic Init
2016-03-18 12:07:35.232 BranchTest[285:22062] Install request timed out
2016-03-18 12:07:45.428 BranchTest[285:22062] SessionRequestError: Operation timed out

I use Branch-Xamarin-Linking-SDK (Version 1.2.1) from Xamarin, component store.
And this is the code, I have in my AppDelegate

```
Branch.Debug = true;
BranchIOS.Init ("<MY_KEY>", url, true);
Branch branch = Branch.GetInstance ();
branch.InitSessionAsync (this);
```

**Comment by antonargunov** [comment]
@venky284 please wait for new version that we will deploy next week

**Comment by dhaligas** [comment]
@antonargunov any time line on when the new version will drop?

**Comment by antonargunov** [comment]
@venky284 I will finish new version today, tomorrow new nuget package will appear, thanks for waiting

**Comment by dhaligas** [comment]
@antonargunov will that be for iOS and Android?

**Comment by antonargunov** [comment]
@dhaligas yes, for both platforms

**Comment by antonargunov** [comment]
Hi guys, we have committed new version of Xamarin SDK.
New Branch' branch named "version_2.1.0" and now we are testing it in any cases even increadibe cases before commit to master:).
If you want you can get that branch and try to incorporate.

**Comment by dhaligas** [comment]
will do did you push to nuget?

**Comment by dhaligas** [comment]
@antonargunov I tried 2.1.0 but my app crashes immediately 

[AppDelegate window]: unrecognized selector sent to instance 0x7a433130

**Comment by antonargunov** [comment]
@venky284 
@dhaligas 
We have uploaded new version of Xamarin SDK and changed documentation.
Try please new version and if you will have any troubles - open new issue please.
Thanks.
