### ISSUE TITLE
Branch IO not working on Android App

### ISSUE THREAD

**Issue by arunprabhus87** [BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK#19]
I am trying to implement Branch IO on My Android App through Xamarin Studio. I followed the steps in intergating the SDK into my Xamarin Studio and created the link in the dash board. I followed the stpes in implementing it in my Splash Activity (Launcher Activity) . The issue is when i try to click on the link created from dashboard it is not navigating to the appliaction. When the app runs the method InitSessionComplete() is getting called sometimes but most of the time SessionRequestError() method is getting called which is always responding with a time out error. Please let me know what i should do to make this work.

**Comment by antonargunov** [comment]
@arunprabhus87 Hello, we finished new version of Xamarin SDK. Wait please, we will publish new version in 2 days.

**Comment by aaustin** [comment]
You can try it here: https://github.com/BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK/tree/version_2.1.0

**Comment by antonargunov** [comment]
@arunprabhus87 We have uploaded new version of Xamarin SDK and changed documentation.
Please try new version and if you will have any troubles - open new issue please.
Thanks.

**Comment by derrickstaten** [comment]
@arunprabhus87 have you had a chance to try this out?

**Comment by arunprabhus87** [comment]
@antonargunov  @derrickstaten @aaustin 
I downloaded the latest update and tried executing the project again. Still am not able to execute it successfully. The follwoing is the github link where i have uploaded the project:

https://github.com/arunprabhus87/BranchIODemo

Plz check and let me know if am missing anything.

**Comment by antonargunov** [comment]
@arunprabhus87 please read this
https://github.com/BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK#android-configure-your-project

Your project has no permissions:
- AccessNetworkState
- Internet

As result: your project can't send/receive something to/from our server and you always have "time out" issue.

Important note: Make sure that your "app uri" is the same as in your dashboard, now in your project you have uri named "branchtest".
