### ISSUE TITLE
iOS [AppDelegate window]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by AntRemo** [BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK#26]
Error  

> [AppDelegate window]: unrecognized selector sent to instance 

occurs after calling 

BranchIOS.Init(_branchKey, options, this);

I tried to figure out the cause...but I could only track it down to an exception occurring at
Branch.g.cs
`InitSessionWithLaunchOptions`
On the following line
`global::ApiDefinition.Messaging.void_objc_msgSend_IntPtr_IntPtr (this.Handle, Selector.GetHandle ("initSessionWithLaunchOptions:andRegisterDeepLinkHandler:"), options.Handle, (IntPtr) block_ptr_callback);
`

Using Xamarin.Forms project.

Oddly enough it works on the TestBed and on a sample project that I created with the same X.Forms version.  In my production app, it fails :(

Any advice would be **greatly** appreciated.

Thanks,
Ant

**Comment by antonargunov** [comment]
@AntRemo check please your parameters,

You can use one of two methods:
Init(String branchKey, NSDictionary launchOptions, IBranchSessionInterface callback)
Init(String branchKey, NSDictionary launchOptions, IBranchBUOSessionInterface callback)

You call:
BranchIOS.Init(_branchKey, options, this)

so, what is "this"?
is "this" a reference to IBranchSessionInterface/IBranchBUOSessionInterface?

**Comment by AntRemo** [comment]
Hi @antonargunov 

Thanks for the super fast reply :+1: 

I am using IBranchSessionInterface.

I tried IBranchBUOSessionInterface as well, but believe that gave me a different error. I can try again if needed.

**Comment by antonargunov** [comment]
@AntRemo I think you did not inherit IBranchSessionInterface.

In my case I declare:
public class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate, IBranchSessionInterface

Then I implement interface methods:
public void InitSessionComplete(Dictionary<string, object> data) {
}

public void SessionRequestError(BranchError error) {
}

Then I call:
....
BranchIOS.Init(_branchKey, options, this)
....

All works.

**Comment by AntRemo** [comment]
Hi @antonargunov 

I first inheritted from AppDelegate, 

`public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate`

then later tried applying the interface to Application

`public partial class App : Application, IBranchSessionInterface`

I was able to get this working super fast on Android.  But iOS is not going as smoothly.

I'm comparing the build settings to see if I can find what is different between the apps that is causing it to crash.

**Comment by AntRemo** [comment]
Applying my build settings caused it to crash in the test app. I'll know more in a few mins :)

**Comment by antonargunov** [comment]
@AntRemo Sorry, I don't know how you make your app's architecture, but in this case you need to use reference to your App class in BranchIOS.Init(...)

Example:
....
App app = new App ();
BranchIOS.Init ("Your Branch key here", launchOptions, app);
LoadApplication (app);
....

**Comment by AntRemo** [comment]
Found the issue.  

If I build with linker OFF, it will crash with this error. 

Setting to SDK assemblies only fixes it.  WOW, that was a ALOT of time troubleshooting that.

**Comment by antonargunov** [comment]
Great!

**Comment by AntRemo** [comment]
@antonargunov is there something that can be done to fix it with the linker off for the future?

I imagine there will be a time where I, or someone else, may need to run with Linker off on device.

Thanks

**Comment by antonargunov** [comment]
@AntRemo I tried to make new iOS application with Xamarin SDK nuget package.
All works with "linker behaviour = Don't Link"

**Comment by AntRemo** [comment]
@antonargunov Ok thanks.

I am NOT on the latest Xamarin iOS or Forms.  So maybe it is something that will be resolved after I update.

**Comment by AntRemo** [comment]
@antonargunov 

I am getting the same error frequently when resuming the app.  If I remove the call to BranchIOS.Init () the error does not occur.

[AppDelegate window]: unrecognized selector sent to instance

Any ideas?

**Comment by AntRemo** [comment]
I have a repo case...

If you replace your App constructor with:

      
public App()
        {
            // The root page of your application
            var tabbedPage = new TabbedPage()
            {
                Children =
                {
                    new ContentPage()
                    {
                        Content = new StackLayout
                        {
                            VerticalOptions = LayoutOptions.Center,
                            Children = { new Button() { Text = "Tap Me", Command = new Command(() =>
                            {
                                NavigationPage.PushAsync(new ContentPage()
                                {
                                    Title = "Second Page",
                                    Content = new WebView()
                                    {
                                        Source = "https://www.google.com",
                                    }
                                });

                            })} 
                            }
                        }
                    }
                }
            };

            NavigationPage = new NavigationPage(tabbedPage);

            Current.MainPage = NavigationPage;
        }


1. Launch the app
2. Tap the button
3. Tap Home
4. Tap the app again. 

Exception will occur.

**Comment by antonargunov** [comment]
@AntRemo sorry but I can't compile that code.
Can you place your test app on github and give me a link?

**Comment by AntRemo** [comment]
Good Day @antonargunov!

Please find a repo @ https://github.com/AntRemo/BranchForms

I also have a bit more details on the error

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[AppDelegate window]: unrecognized selector sent to instance 0x14eb7230

Native stack trace:

	0   CoreFoundation                      0x22138123 <redacted> + 150

	1   libobjc.A.dylib                     0x218dee17 objc_exception_throw + 38

	2   CoreFoundation                      0x2213d925 <redacted> + 0

	3   CoreFoundation                      0x2213b3fb <redacted> + 350

	4   CoreFoundation                      0x2206bc08 _CF_forwarding_prep_0 + 24

	5   BranchFormsTestiOS                  0x0115dcb9 -[BNCStrongMatchHelper presentSafariVCWithBranchKey:] + 832

	6   BranchFormsTestiOS                  0x0115d953 -[BNCStrongMatchHelper createStrongMatchWithBranchKey:] + 250

	7   BranchFormsTestiOS                  0x01146ca3 -[Branch registerInstallOrOpen:] + 250

	8   BranchFormsTestiOS                  0x01146ba5 -[Branch initializeSession] + 280

	9   CoreFoundation                      0x220ece9d <redacted> + 12

	10  CoreFoundation                      0x220ec8a7 <redacted> + 390

	11  CoreFoundation                      0x220ec685 <redacted> + 40

	12  CoreFoundation                      0x221402db <redacted> + 1334

	13  CoreFoundation                      0x2204ea53 _CFXNotificationPost + 486

	14  Foundation                          0x2287a95f <redacted> + 74

	15  UIKit                               0x262fc11b <redacted> + 1150

	16  UIKit                               0x26512949 <redacted> + 104

	17  FrontBoardServices                  0x2340f637 <redacted> + 158

	18  Foundation                          0x2291b1e7 <redacted> + 446

	19  Foundation                          0x228a635f <redacted> + 66

	20  BaseBoard                           0x233a8b8b <redacted> + 102

	21  FrontBoardServices                  0x2340aba7 <redacted> + 94

	22  FrontBoardServices                  0x2340f4a5 <redacted> + 308

	23  UIKit                               0x265130ef <redacted> + 170

	24  UIKit                               0x26512db9 <redacted> + 644

	25  FrontBoardServices                  0x23401a59 <redacted> + 40

	26  FrontBoardServices                  0x2341cc7f <redacted> + 230

	27  FrontBoardServices                  0x2341cf71 <redacted> + 48

	28  CoreFoundation                      0x220fb68f <redacted> + 14

	29  CoreFoundation                      0x220fb27d <redacted> + 452

	30  CoreFoundation                      0x220f95eb <redacted> + 794

	31  CoreFoundation                      0x2204cbf9 CFRunLoopRunSpecific + 520

	32  CoreFoundation                      0x2204c9e5 CFRunLoopRunInMode + 108

	33  GraphicsServices                    0x23298ac9 GSEventRunModal + 160

	34  UIKit                               0x262dcba1 UIApplicationMain + 144

	35  BranchFormsTestiOS                  0x00bba5cc wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 272

	36  BranchFormsTestiOS                  0x00b30184 UIKit_UIApplication_Main_string___intptr_intptr + 52

	37  BranchFormsTestiOS                  0x00b30144 UIKit_UIApplication_Main_string___string_string + 204

	38  BranchFormsTestiOS                  0x000c70a8 BranchFormsTest_iOS_Application_Main_string__ + 152

	39  BranchFormsTestiOS                  0x003231f8 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 256

	40  BranchFormsTestiOS                  0x0118bf2f mono_jit_runtime_invoke + 1150

	41  BranchFormsTestiOS                  0x011cda05 mono_runtime_invoke + 88

	42  BranchFormsTestiOS                  0x011d0e6b mono_runtime_exec_main + 282

	43  BranchFormsTestiOS                  0x0123e138 xamarin_main + 2072

	44  BranchFormsTestiOS                  0x0113dff9 main + 112

	45  libdyld.dylib                       0x21cfb873 <redacted> + 2

Thanks very much :)
Ant

**Comment by antonargunov** [comment]
@AntRemo
add please
BranchIOS.Debug = true;

before
BranchIOS.Init(_branchKey, options, this);

I will investigate what is happens without enabling Debug mode.

**Comment by AntRemo** [comment]
@antonargunov 

Thanks for the workaround! :+1:

**Comment by AntRemo** [comment]
Hi @antonargunov!

I was wondering if you made any progress in resolving this.

I'd like to release with this feature, however, I do not want to release with Debug enabled.

Thanks,
Ant

**Comment by ahmednawar** [comment]
@AntRemo @antonargunov 

In the `AppDelegate.cs` file, I am not sure where the `window` object is defined/instantiated. Can you check if this object exists?

**Comment by AntRemo** [comment]
Hi @ahmedanawar

I think it is handled by the Xamarin.Forms framework.

Unfortunately, I do not know enough about how it works to provide more info.

**Comment by antonargunov** [comment]
@ahmednawar 
Solution: BranchFormsTest.iOS
File: AppDelegate.cs
Row 26: var commonApp = new App();

Solution: BranchFormsTest
File: App.cs
Row 18: var tabbedPage = new TabbedPage() ..... etc.

**Comment by ahmednawar** [comment]
@antonargunov does this bug occur for all projects on Xamarin?

**Comment by antonargunov** [comment]
@ahmednawar this bug occurs only if you move to NavigationPage that contain WebView (iOS); if you will not move to NavigationPage that contain WebView - all works

**Comment by AntRemo** [comment]
Hi @antonargunov

To add, I can make it occur in my app without navigating to a webview, however, I found it also crashes with a webview as well.

**Comment by ahmednawar** [comment]
@antonargunov which core iOS library version do you use? We changed something in our latest release v 0.12.1 that deals with window objects that might fix this problem

**Comment by antonargunov** [comment]
@ahmednawar 0.11.18 I guess

**Comment by antonargunov** [comment]
@ahmednawar as I understand I need to update iOS lib, right?

**Comment by ahmednawar** [comment]
@antonargunov yeah, let's see if this fixes the problem

**Comment by antonargunov** [comment]
@AntRemo wait please new version of Xamarin SDK

**Comment by AntRemo** [comment]
Hi @antonargunov 

Sorry I misunderstand.  Would you like me to wait or upgrade to the latest Xamarin SDK?

Thanks

**Comment by antonargunov** [comment]
@AntRemo I meant - wait, I will ping you when I will have new version

**Comment by AntRemo** [comment]
@antonargunov Ok cool :)

**Comment by MatFillion** [comment]
For what it's worth, I have the same exception in our Xamarin (not forms) application. Application launches properly but if I minimize it, when bringing it back to the foreground it crashes with that exception. I'll be waiting for the update you are talking about.

**Comment by antonargunov** [comment]
@MatFillion it will be the best if you ping our support team and send test project where we can reproduce the issue. After I will finish new version I will be able to test and if issue will occur then we will b able to continue fixing without delay.

But if you don't want to create test project, just wait until I will finish new version.
Thanks!

**Comment by AntRemo** [comment]
Hi @antonargunov 

Just checking in for a status update. :)

Thanks,
Ant

**Comment by antonargunov** [comment]
Hi @AntRemo I have committed new version of Xamarin SDK.
You can download nuget package from github and update form your local source or wait until we upload package to nuget.org

Btw, I have checked your test project, I have no exceptions. Try please and write me something :).

**Comment by AntRemo** [comment]
Thanks @antonargunov !!! :)

I've never updated from a local nuget source, so I'll have to learn that first. :)

**Comment by aaustin** [comment]
I've updated the production nuget file!

**Comment by antonargunov** [comment]
@AntRemo  we have uploaded to nuget.org :)

**Comment by AntRemo** [comment]
@aaustin @antonargunov  Awesome!!! THANKS :) I'll test now

**Comment by AntRemo** [comment]
@antonargunov @ahmednawar @aaustin Works great now!!! 👍 :) 

Thanks so much for the fast turnaround and great service.  I appreciate it!

All the best,
Ant

**Comment by antonargunov** [comment]
@AntRemo @MatFillion 
I hope all works nice!
Good luck!
