### ISSUE TITLE
Xamarin.Android SDK - cannot initialize with an Application context

### ISSUE THREAD

**Issue by wis-jellis** [BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK#27]
Hi, in the doc here:
https://dev.branch.io/getting-started/sdk-integration-guide/guide/xamarin/#start-a-branch-session

section 4 states: Add calls to the OnCreate and OnNewIntent methods of either your Application class or the first Activity you start

I'm not using Xamarin.Forms, I'm using Xamarin.Android, but same documentation seems to apply here:
https://dev.branch.io/getting-started/sdk-integration-guide/advanced/xamarin/#initialization-for-non-forms-apps

My preference is to use initialization in my Application class - to handle various scenarios in our app that may not run through particular Activities (like sharing from a pending intent of a push notification display).

Unfortunately, it seems this is not really supported, based on code here:
https://github.com/BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK/blob/master/Branch-Xamarin-SDK.Droid/BranchAndroid.cs

line 69:((Activity)context).Application.RegisterActivityLifecycleCallbacks (instance.lifeCycleHandler);

it is assuming that the context passed in is always an Activity and casting to that.  Can this be adjusted to take an Application OR an Activity? and register the lifecycle callbacks appropritately? (i.e. Application.RegisterActivityLifecycleCallbacks in my case)?

Thanks

**Comment by antonargunov** [comment]
Hello @wis-jellis,
I will add a method with parameter Application.

Branch need to know ApplicationContext and I will receive it from Application, or will you set it by yourself? need I add one more parameter to set ApplicationContext?

**Comment by wis-jellis** [comment]
Hi @antonargunov, I would suggest using the ApplicationContext from the Application instance passed in, if possible.

app.ApplicationContext

Thanks,
James

**Comment by antonargunov** [comment]
Hi @wis-jellis, I have committed new version of Xamarin SDK.
You can download nuget package from github and update form your local source or wait until we upload package to nuget.org

I added Init with Application, please try.

**Comment by antonargunov** [comment]
@wis-jellis we have uploaded new package to nuget.org

**Comment by wis-jellis** [comment]
great, thank you! I will try it out.

**Comment by antonargunov** [comment]
@wis-jellis I hope all works nice.
If you will need something else - open please new issue.
Good luck!
