### ISSUE TITLE
NullPointerException in SetNewUrl

### ISSUE THREAD

**Issue by kostub** [BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK#6]
The following function
```C#
BranchIOS.getInstance().SetNewUrl(url);
```
throws a null pointer exception when called with a URL with no Query string. This happens for Facebook login URLs for instance.

You can work around this bug by just wrapping it up with:
```C#
if (url != null && url.Query != null)
{
       BranchIOS.getInstance().SetNewUrl(url);
}
```

The following code needs to be fixed on line 45 of BranchIOS.cs

It currently does:
```C#
void processUrl(NSUrl url) {
   if (url != null) {
      foreach (string query in url.Query.Split (new [] { '&' })) {
                     ...
      }
   }
}
```

Instead it should be:

```C#
void processUrl(NSUrl url) {
   if (url != null && url.Query != null) {
      foreach (string query in url.Query.Split (new [] { '&' })) {
                     ...
      }
   }
}
```

**Comment by aaustin** [comment]
@kostub Please try v1.2.0 as this should be addressed.
