### ISSUE TITLE
Missing continueUserActivity support for iOS universal app links

### ISSUE THREAD

**Issue by dhaligas** [BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK#9]
It appears this function is missing in the Xamarin sdk for branch.  We need this to support universal app links for iOS

- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
    BOOL handledByBranch = [[Branch getInstance] continueUserActivity:userActivity];
    
    return handledByBranch;
}

**Comment by aaustin** [comment]
@dhaligas We just released version 2.0 with full support for continue user activity. Please check it out. https://github.com/BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK#ios-with-forms

**Comment by dhaligas** [comment]
Thanks!  Will check it out tomorrow.
